// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjon0a1xPpv1DH7WzKHo7TErV-OQ17I1M',
    appId: '1:466189418219:web:579f84879cbcbc38dc88ae',
    messagingSenderId: '466189418219',
    projectId: 'bangkaew-98c9d',
    authDomain: 'bangkaew-98c9d.firebaseapp.com',
    storageBucket: 'bangkaew-98c9d.appspot.com',
    measurementId: 'G-BR03B8VVZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bwbgVA0cQLo_0X8T9XjVcKSaEXgNoPg',
    appId: '1:466189418219:android:b9b952aec517c48fdc88ae',
    messagingSenderId: '466189418219',
    projectId: 'bangkaew-98c9d',
    storageBucket: 'bangkaew-98c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm-YcC3NxNQCnIConFxCuueX2wfCsGHxg',
    appId: '1:466189418219:ios:48699d25b5198cc5dc88ae',
    messagingSenderId: '466189418219',
    projectId: 'bangkaew-98c9d',
    storageBucket: 'bangkaew-98c9d.appspot.com',
    androidClientId: '466189418219-282d441i48aspnit7gl24cabsk9fsnjl.apps.googleusercontent.com',
    iosClientId: '466189418219-a3eucb2lb8o85e4kf2pfm7bph1vmjnft.apps.googleusercontent.com',
    iosBundleId: 'com.nithikornwarapork.bangkaew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm-YcC3NxNQCnIConFxCuueX2wfCsGHxg',
    appId: '1:466189418219:ios:48699d25b5198cc5dc88ae',
    messagingSenderId: '466189418219',
    projectId: 'bangkaew-98c9d',
    storageBucket: 'bangkaew-98c9d.appspot.com',
    androidClientId: '466189418219-282d441i48aspnit7gl24cabsk9fsnjl.apps.googleusercontent.com',
    iosClientId: '466189418219-a3eucb2lb8o85e4kf2pfm7bph1vmjnft.apps.googleusercontent.com',
    iosBundleId: 'com.nithikornwarapork.bangkaew',
  );
}
